# æœºåœºè®¢é˜…ï¼Œåç§°ä¸èƒ½é‡å¤
proxy-providers:
  Airport_01:NCloud
    type: http
    interval: 1800
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ğŸ¯ å…¨çƒç›´è¿
    url: ""
      
# ç”¨äºä¸‹è½½è®¢é˜…æ—¶æŒ‡å®šUA
#global-ua: meta
    
# å…¨å±€é…ç½®
# port: 7890
# socks-port: 7891
# redir-port: 7892
# mixed-port: 7893
# tproxy-port: 7894
# ipv6: false
# allow-lan: true
# unified-delay: true
# tcp-concurrent: true
  
# geodata-mode: false
# geodata-loader: standard
# geo-auto-update: true
# geo-update-interval: 48
# geox-url:
#   geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
#   geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
#   mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
#   asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"
  
# æ§åˆ¶é¢æ¿
# external-controller: 0.0.0.0:9090
# secret: ""
# external-ui: ui
# external-ui-url: "https://ghp.ci/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

# åŒ¹é…è¿›ç¨‹ always/strict/off
# find-process-mode: strict
# global-client-fingerprint: chrome
# keep-alive-idle: 600
# keep-alive-interval: 30

# ç­–ç•¥ç»„é€‰æ‹©å’Œfakeipç¼“å­˜
# profile:
#   store-selected: true
#   store-fake-ip: true
  
# æµé‡å—…æ¢
# sniffer:
#   enable: true
#   sniff:
#     HTTP:
#       ports: [80, 8080-8880]
#       override-destination: true
#     TLS:
#       ports: [443, 8443]
#     QUIC:
#       ports: [443, 8443]
#   force-domain:
#     - +.v2ex.com
#   skip-domain:
#     - "Mijia Cloud"
#     - "dlg.io.mi.com"
#     - "+.push.apple.com"
#     - "+.apple.com"
    
# ä»£ç†æ¨¡å¼
# tun:
#   enable: true
#   stack: mixed
#   mtu: 9000
#   dns-hijack:
#     - "any:53"
#     - "tcp://any:53"
#   auto-route: true
#   auto-redirect: true
#   auto-detect-interface: true
  
# DNSæ¨¡å—
# dns:
#   enable: true
#   listen: 0.0.0.0:1053
#   ipv6: false
#   respect-rules: true
# æ¨¡å¼åˆ‡æ¢ redir-host / fake-ip
#   enhanced-mode: fake-ip
#   fake-ip-range: 28.0.0.1/8
# æ¨¡å¼åˆ‡æ¢ whitelist/blacklist 
# é»‘åå•æ¨¡å¼è¡¨ç¤ºå¦‚æœåŒ¹é…æˆåŠŸåˆ™ä¸è¿”å› Fake-IP, ç™½åå•æ¨¡å¼æ—¶åªæœ‰åŒ¹é…æˆåŠŸæ‰è¿”å› Fake-IP
#   fake-ip-filter-mode: blacklist
#   fake-ip-filter:
#     - "+.lan"
#     - "+.local"
#     - geosite:private
#     - geosite:cn
#   default-nameserver:
#     - 223.5.5.5
#     - 119.29.29.29
#   proxy-server-nameserver:
#     - 223.5.5.5
#     - 119.29.29.29
#   nameserver:
#     - 223.5.5.5
#     - 119.29.29.29
#   nameserver-policy:
#     "rule-set:private_domain,cn_domain":
#       - 223.5.5.5
#       - 119.29.29.29
#     "rule-set:geolocation-!cn":
#       - "https://dns.cloudflare.com/dns-query"
#       - "https://dns.google/dns-query"
 
   
proxies:
- name: "ğŸ¯ å…¨çƒç›´è¿"
  type: direct
  udp: true
 
# é”šç‚¹
pr: &pr {type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨, ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡è‡ªåŠ¨, ğŸ‡¹ğŸ‡¼ å°æ¹¾è‡ªåŠ¨, ğŸ‡ºğŸ‡¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ğŸ¯ å…¨çƒç›´è¿]}
# ç­–ç•¥ç»„
proxy-groups:
  - {name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©, type: select, proxies: [ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨, ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡è‡ªåŠ¨, ğŸ‡¹ğŸ‡¼ å°æ¹¾è‡ªåŠ¨, ğŸ‡ºğŸ‡¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ğŸ¯ å…¨çƒç›´è¿]}
  - {name: ğŸ“¹ YouTube,!!merge <<: *pr}
  - {name: ğŸ€ Google,!!merge <<: *pr}
  - {name: ğŸ¤– ChatGPT,!!merge <<: *pr}
  - {name: ğŸ‘¨ğŸ¿â€ğŸ’» GitHub,!!merge <<: *pr}
  - {name: ğŸ¬ OneDrive,!!merge <<: *pr}
  - {name: ğŸªŸ Microsoft,!!merge <<: *pr}
  - {name: ğŸµ TikTok,!!merge <<: *pr}
  - {name: ğŸ“² Telegram,!!merge <<: *pr}
  - {name: ğŸ¥ NETFLIX,!!merge <<: *pr}
  - {name: ğŸ¥ DisneyPlus,!!merge <<: *pr}
  - {name: ğŸ® æ¸¸æˆå¹³å°,!!merge <<: *pr}
  - {name: ğŸ“º Bahamut,!!merge <<: *pr}
  - {name: ğŸŒ å›½å¤–åª’ä½“,!!merge <<: *pr}
  - {name: âœˆï¸ Speedtest,!!merge <<: *pr}
  - {name: ğŸ•Šï¸ Twitter,!!merge <<: *pr}
  - {name: ğŸ Apple, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ¯ å…¨çƒç›´è¿, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼,!!merge <<: *pr}
  - {name: ğŸ”¯ é¦™æ¸¯æ•…è½¬, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(æ¸¯|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(æ¸¯|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"}
  - {name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(æ–°|SG|(?i)Singapore))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾)).)*$" }
  - {name: ğŸ‡¹ğŸ‡¼ å°æ¹¾è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(å°|TW|(?i)Taiwan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾)).)*$" }
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(ç¾|US|(?i)States|America))^((?!(æ¸¯|å°|æ—¥|éŸ©|æ–°)).)*$"}
  - {name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "^((?!(ç›´è¿)).)*$"}
  - {name: ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, type: select, include-all: true}
rules:
  - RULE-SET,Lan_Domain,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Lan_IP,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Direct_Domain,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Custom_Direct,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Custom_Proxy,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,GoogleFCM_Domain,ğŸ€ Google
  - RULE-SET,GoogleFCM_IP,ğŸ€ Google
  - RULE-SET,GoogleCN,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,GoogleCNProxy_IP,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,SteamCN_Domain,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Steam_CDN,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,PrivateTracker_Domain,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,PrivateTracker_IP,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Telegram_Domain,ğŸ“² Telegram
  - RULE-SET,Telegram_IP,ğŸ“² Telegram
  - RULE-SET,Twitter_Domain,ğŸ•Šï¸ Twitter
  - RULE-SET,Twitter_IP,ğŸ•Šï¸ Twitter
  - RULE-SET,OpenAI_Domain,ğŸ¤– ChatGPT
  - RULE-SET,OpenAI_IP,ğŸ¤– ChatGPT
  - RULE-SET,Copilot_Domain,ğŸ¤– ChatGPT
  - RULE-SET,Copilot_IP,ğŸ¤– ChatGPT
  - RULE-SET,Speedtest_Domain,âœˆï¸ Speedtest
  - RULE-SET,Apple_OCD_Domain.mrs,ğŸ Apple
  - RULE-SET,Apple_OCD_IP,ğŸ Apple
  - RULE-SET,Microsoft_Domain,ğŸªŸ Microsoft
  - RULE-SET,YouTube_Domain,ğŸ“¹ YouTube
  - RULE-SET,YouTube_IP,ğŸ“¹ YouTube
  - RULE-SET,Google_Domain,ğŸ€ Google
  - RULE-SET,Google_IP,ğŸ€ Google
  - RULE-SET,TikTok_Domain,ğŸµ TikTok
  - RULE-SET,Netflix_Domain,ğŸ¥ NETFLIX
  - RULE-SET,Netflix_IP,ğŸ¥ NETFLIX
  - RULE-SET,Disney_Domain,ğŸ¥ DisneyPlus
  - RULE-SET,Spotify_Domain,ğŸ» Spotify
  - RULE-SET,Spotify_IP,ğŸ» Spotify
  - RULE-SET,Bahamut_Domain,ğŸ“º Bahamut
  - RULE-SET,GlobalMedia_Domain,ğŸŒ å›½å¤–åª’ä½“
  - RULE-SET,GlobalMedia_IP,ğŸŒ å›½å¤–åª’ä½“
  - RULE-SET,Epic_Domain,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,EA_Domain,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Blizzard_Domain,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Blizzard_IP,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,UBI_Domain,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Sony_Domain,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Nintendo_Domain,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Nintendo_IP,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Steam_Domain,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,GlobalMedia_IP,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Proxy_Domain,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,Proxy_IP,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,China_OCD_Domain,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,China_OCD_IP,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,ChinaCompany_IP,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,ChinaIPs_IP,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Download_Domain,ğŸ¯ å…¨çƒç›´è¿
  - GEOSITE,category-public-tracker,ğŸ¯ å…¨çƒç›´è¿
  - GEOIP,LAN,ğŸ¯ å…¨çƒç›´è¿,no-resolve
  - GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿,no-resolve
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  qcy: &qcy {type: http, interval: 86400, behavior: domain, format: text}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  Lan_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Lan/Lan_OCD_Domain.mrs"}
  Lan_IP: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Lan/Lan_OCD_IP.mrs"}
  Direct_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Direct/Direct_OCD_Domain.mrs"}
  Custom_Direct: {!!merge <<: *class, url: "https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Custom_Direct.list"}
  Custom_Proxy: {!!merge <<: *class, url: "https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Custom_Proxy.list"}
  GoogleFCM_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/GoogleFCM/GoogleFCM_OCD_Domain.mrs"}
  GoogleFCM_IP: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/GoogleFCM/GoogleFCM_OCD_IP.mrs"}
  GoogleCN: {!!merge <<: *class, url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list"}
  GoogleCNProxy_IP: {!!merge <<: *class, url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list"}
  SteamCN_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/SteamCN/SteamCN_OCD_Domain.mrs"}
  Steam_CDN: {!!merge <<: *class, url: "https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Steam_CDN.list"}
  PrivateTracker_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/PrivateTracker/PrivateTracker_OCD_Domain.mrs"}
  PrivateTracker_IP: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/PrivateTracker/PrivateTracker_OCD_IP.mrs"}
  Telegram_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Telegram/Telegram_OCD_Domain.mrs"}
  Telegram_IP: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Telegram/Telegram_OCD_IP.mrs"}
  Twitter_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Twitter/Twitter_OCD_Domain.mrs"}
  Twitter_IP: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Twitter/Twitter_OCD_IP.mrs"}
  OpenAI_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/OpenAI/OpenAI_OCD_Domain.mrs"}
  OpenAI_IP: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/OpenAI/OpenAI_OCD_IP.mrs"}
  Copilot_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Copilot/Copilot_OCD_Domain.mrs"}
  Copilot_IP: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Copilot/Copilot_OCD_IP.mrs"}
  GitHub_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/GitHub/GitHub_OCD_Domain.mrs"}
  Speedtest_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Speedtest/Speedtest_OCD_Domain.mrs"}
  Apple_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Apple/Apple_OCD_Domain.mrs"}
  Apple_IP: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Apple/Apple_OCD_IP.mrs"}
  Microsoft_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Microsoft/Microsoft_OCD_Domain.mrs"}
  YouTube_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/YouTube/YouTube_OCD_Domain.mrs"}
  YouTube_IP: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/YouTube/YouTube_OCD_IP.mrs"}
  Google_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Google/Google_OCD_Domain.mrs"}
  Google_IP: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Google/Google_OCD_IP.mrs"}
  TikTok_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/TikTok/TikTok_OCD_Domain.mrs"}
  Netflix_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Netflix/Netflix_OCD_Domain.mrs"}
  Netflix_IP: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Netflix/Netflix_OCD_IP.mrs"}
  Disney_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Disney/Disney_OCD_Domain.mrs"}
  Spotify_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Spotify/Spotify_OCD_Domain.mrs"}
  Spotify_IP.mrs: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Spotify/Spotify_OCD_IP.mrs"}
  Bahamut_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Bahamut/Bahamut_OCD_Domain.mrs"}
  GlobalMedia_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/GlobalMedia/GlobalMedia_OCD_Domain.mrs"}
  GlobalMedia_IP: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/GlobalMedia/GlobalMedia_OCD_IP.mrs"}
  Epic_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Epic/Epic_OCD_Domain.mrs"}
  EA_Domain.mrs: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/EA/EA_OCD_Domain.mrs"}
  Blizzard_Domain.mrs: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Blizzard/Blizzard_OCD_Domain.mrs"}
  Blizzard_IP: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Blizzard/Blizzard_OCD_IP.mrs"}
  UBI_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/UBI/UBI_OCD_Domain.mrs"}
  Sony_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Sony/Sony_OCD_Domain.mrs"}
  Nintendo_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Nintendo/Nintendo_OCD_Domain.mrs"}
  Nintendo_IP: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Nintendo/Nintendo_OCD_IP.mrs"}
  Steam_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Steam/Steam_OCD_Domain.mrs"}
  Proxy_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Proxy/Proxy_OCD_Domain.mrs"}
  Proxy_IP: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Proxyo/Proxy_OCD_IP.mrs"}
  China_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/China/China_OCD_Domain.mrs"}
  China_IP: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/China/China_OCD_IP.mrs"}
  ChinaCompany_IP: {!!merge <<: *class, url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list"}
  ChinaIPs_IP: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/ChinaIPs/ChinaIPs_OCD_IP.mrs"}
  Download_Domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Download/Download_OCD_Domain.mrs"}

